version: '3.1'

services:
  api:
    container_name: api-rpg
    build: ./
    ports:
      - 5000:5000
    platform: linux/x86_64
    working_dir: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=rpgdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5